version: '3.5' 


services: 

  postgres: 
    container_name: postgres_container 
    image: postgres
    environment: 
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: ChangeMe 
      # PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: app
    volumes: 
      - postgres:/var/lib/postgresql/:rw
      - ./db/:/var/lib/postgresql/:rw
    ports: 
      - "5432:5432" 
    networks: 
      - symfony 
    restart: unless-stopped 

  pgadmin: 
    container_name: pgadmin_container 
    image: dpage/pgadmin4 
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org} 
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin} 
      PGADMIN_CONFIG_SERVER_MODE: 'False' 
    volumes: 
      - pgadmin:/var/lib/pgadmin:rw
      - ./pgadmin:/var/lib/pgadmin:rw
    ports: 
      - "${PGADMIN_PORT:-5050}:80" 
    networks: 
      - symfony 

    restart: unless-stopped 

  maildev:
    image: maildev/maildev
    container_name: maildev_docker_symfony
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
        - symfony


networks: 
  symfony: 
    driver: 
      bridge 

volumes: 
  postgres: 
  pgadmin: