<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCzjrCJV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCzjrCJV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCzjrCJV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCzjrCJV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCzjrCJV\App_KernelDevDebugContainer([
    'container.build_hash' => 'CzjrCJV',
    'container.build_id' => 'be04d1a7',
    'container.build_time' => 1638262521,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCzjrCJV');
