<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxWUxtb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxWUxtb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxWUxtb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxWUxtb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxWUxtb\App_KernelDevDebugContainer([
    'container.build_hash' => 'XxWUxtb',
    'container.build_id' => 'f6bfe567',
    'container.build_time' => 1638204410,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxWUxtb');
