<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2Rs3xty\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2Rs3xty/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2Rs3xty.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2Rs3xty\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2Rs3xty\App_KernelDevDebugContainer([
    'container.build_hash' => '2Rs3xty',
    'container.build_id' => '150b26ff',
    'container.build_time' => 1638207891,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2Rs3xty');
